const cardsArray = [
    {id: 1, name: 'As Pik', picture: 'as_pik.png'},
    {id: 2, name: 'Dwójka Pik', picture: '2_pik.png'},
    {id: 3, name: 'Trójka Pik', picture: '3_pik.png'},
    {id: 4, name: 'Czwórka Pik', picture: '4_pik.png'},
    {id: 5, name: 'Piątka Pik', picture: '5_pik.png'},
    {id: 6, name: 'Szóstka Pik', picture: '6_pik.png'},
    {id: 7, name: 'Siódemka Pik', picture: '7_pik.png'},
    {id: 8, name: 'Ósemka Pik', picture: '8_pik.png'},
    {id: 9, name: 'Dziewiątka Pik', picture: '9_pik.png'},
    {id: 10, name: 'Dziesiątka Pik', picture: '10_pik.png'},
    {id: 11, name: 'Walet Pik', picture: 'walet_pik.png'},
    {id: 12, name: 'Dama Pik', picture: 'quenn_pik.png'},
    {id: 13, name: 'Król Pik', picture: 'king_pik.png'},

    {id: 14, name: 'As Kier', picture: 'as_kier.png'},
    {id: 15, name: 'Dwójka Kier', picture: '2_kier.png'},
    {id: 16, name: 'Trójka Kier', picture: '3_kier.png'},
    {id: 17, name: 'Czwórka Kier', picture: '4_kier.png'},
    {id: 18, name: 'Piątka Kier', picture: '5_kier.png'},
    {id: 19, name: 'Szóstka Kier', picture: '6_kier.png'},
    {id: 20, name: 'Siódemka Kier', picture: '7_kier.png'},
    {id: 21, name: 'Ósemka Kier', picture: '8_kier.png'},
    {id: 22, name: 'Dziewiątka Kier', picture: '9_kier.png'},
    {id: 23, name: 'Dziesiątka Kier', picture: '10_kier.png'},
    {id: 24, name: 'Walet Kier', picture: 'walet_kier.png'},
    {id: 25, name: 'Dama Kier', picture: 'quenn_kier.png'},
    {id: 26, name: 'Król Kier', picture: 'king_kier.png'},

    {id: 27, name: 'As Trefl', picture: 'as_trefl.png'},
    {id: 28, name: 'Dwójka Trefl', picture: '2_trefl.png'},
    {id: 29, name: 'Trójka Trefl', picture: '3_trefl.png'},
    {id: 30, name: 'Czwórka Trefl', picture: '4_trefl.png'},
    {id: 31, name: 'Piątka Trefl', picture: '5_trefl.png'},
    {id: 32, name: 'Szóstka Trefl', picture: '6_trefl.png'},
    {id: 33, name: 'Siódemka Trefl', picture: '7_trefl.png'},
    {id: 34, name: 'Ósemka Trefl', picture: '8_trefl.png'},
    {id: 35, name: 'Dziewiątka Trefl', picture: '9_trefl.png'},
    {id: 36, name: 'Dziesiątka Trefl', picture: '10_trefl.png'},
    {id: 37, name: 'Walet Trefl', picture: 'walet_trefl.png'},
    {id: 38, name: 'Dama Trefl', picture: 'quenn_trefl.png'},
    {id: 39, name: 'Król Trefl', picture: 'king_trefl.png'},

    {id: 40, name: 'As Karo', picture: 'as_karo.png'},
    {id: 41, name: 'Dwójka Karo', picture: '2_karo.png'},
    {id: 42, name: 'Trójka Karo', picture: '3_karo.png'},
    {id: 43, name: 'Czwórka Karo', picture: '4_karo.png'},
    {id: 44, name: 'Piątka Karo', picture: '5_karo.png'},
    {id: 45, name: 'Szóstka Karo', picture: '6_karo.png'},
    {id: 46, name: 'Siódemka Karo', picture: '7_karo.png'},
    {id: 47, name: 'Ósemka Karo', picture: '8_karo.png'},
    {id: 48, name: 'Dziewiątka Karo', picture: '9_karo.png'},
    {id: 49, name: 'Dziesiątka Karo', picture: '10_karo.png'},
    {id: 50, name: 'Walet Karo', picture: 'walet_karo.png'},
    {id: 51, name: 'Dama Karo', picture: 'quenn_karo.png'},
    {id: 52, name: 'Król Karo', picture: 'king_karo.png'},
];